### ISSUE TITLE
PDB loading?

### ISSUE THREAD

**Issue by bekoha** [mborgerson/ghidra-xbe#17]
With more and more debug builds appearing online, would be nice to see PDB loading support. For example, Starcraft: Ghost and Tom Clancy's Ghost Recon 2 both have matching .pdbs alongside .xbes that seem to match with offsets counted from the beginning of .text memory block and Gauntlet: Dark Legacy doesn't seem to match at all despite being mentioned in multiple places online. Using the "Load PDB File" option makes an "Incomplete PDB information" error pop up and there's no way to force loading it anyway; Microsoft's own [cvdump](https://github.com/microsoft/microsoft-pdb/tree/master/cvdump) dumps PDB mostly successfully.

**Comment by mborgerson** [comment]
Loading PDBs is a feature of Ghidra on Windows. You'll probably want to load a PDB against the corresponding .exe, file instead of the .xbe. If you're having trouble loading a particular PDB file, I recommend filing an issue against the main Ghidra repository.
