### ISSUE TITLE
Attempt to read beyond EOF

### ISSUE THREAD

**Issue by thrimbor** [mborgerson/ghidra-xbe#21]
Somewhere the plugin tries to read from the xbe beyond EOF, causing an error in the Ghidra log.

For example when opening the Counter-Strike xbe (its size is 3,973,120 bytes):
![Screenshot_20201218_160839](https://user-images.githubusercontent.com/1339483/102629517-900c2600-414b-11eb-940a-3dbfba260a08.png)

**Comment by x1nixmzeng** [comment]
I'm seeing the same error:

`2021-02-26 | 22:52:15 | ERROR | (XbeLoader) EOF: unable to read 2240544 bytes at 3321856`

Downloaded the prebuilt release :https://github.com/mborgerson/ghidra-xbe/releases/tag/build-202102142037

Ghidra v9.2.2
Java 15.0.2
