### ISSUE TITLE
XbSymbolDatabaseTool missing execute permission on Linux

### ISSUE THREAD

**Issue by thrimbor** [mborgerson/ghidra-xbe#27]
There's an issue that happened to me a few times, but interestingly not always: The XbSymbolDatabaseTool embedded in the plugin fails to run because it's missing the execute flag. Unfortunately, Ghidra plugins are shipped as zip files, so all unix-permissions on the files get lost, which is causing this issue.

It may be necessary to add a piece of code to the plugin that checks and sets the execute flag for the binary. In the meantime, this works as a temporary workaround:
```sh
chmod +x ~/.ghidra/.ghidra_9.2.2_DEV/Extensions/ghidra-xbe/os/linux64/XbSymbolDatabaseTool
```

The path needs to be adjusted to the Ghidra version that is affected. This problem may also affect macOS.

**Comment by RadWolfie** [comment]
Correct me if I'm wrong. It should fall under Ghidra's extension installer system to set executable flag as it use zip files.

**Comment by databoose** [comment]
### I am re opening this issue as i believe this is could be a bug, the build process does chmod +x XbSymbolDatabaseTool properly, and when i had checked (as i was having this issue myself), the file had already been set to executable.

**OP's workaround did not work for me.**, so i figured this should be investigated further.

> Correct me if I'm wrong. It should fall under Ghidra's extension installer system to set executable flag as it use zip files.

Correct, infact in the very build process (build.sh) when compiling from source, it is given executable permissions automatically,  ,so this should not be the issue, however the error is still displayed for me  : 

![image](https://github.com/user-attachments/assets/dc6edb85-4dc5-4122-949d-95ce4e01b156)

Upon looking through ghidra user debug logs, i could find nothing actually referrencing XBSymbolDatabaseTool to maybe get an idea as to what is going on, so my next step was to download the source of this repo and grep the string.

![image](https://github.com/user-attachments/assets/27975777-8fad-413b-89c0-692ccd402c6b)

Essentially, to my understanding at least, XbSymbolDatabaseTool is within the following file : 

https://github.com/XboxDev/ghidra-xbe/blob/master/src/main/java/XbeLoader/XbeXbSymbolDatabaseAnalyzer.java

In the following code here, starting from line 123 , some type of exception is caught, and thus this exact error message is displayed (i could not find an occurence of this error message anywhere else within the entire repo, so pretty sure we narrowed it down here)

```java    
                } catch (InterruptedException e) {
			log.appendMsg("Failed to run " + toolExec);
			return false;
		} catch (IOException e) {
			log.appendMsg("Failed to run " + toolExec);
			return false;
		} catch (InvalidInputException e) {
			log.appendMsg("Failed to run " + toolExec);
			return false;
               }
